name: Build P9PXL_SukiSU Ultra
on:
  workflow_dispatch:
    inputs:
      SUSFS_CI:
        type: choice
        description: "下载SUSFS模块调用方式"
        required: true
        default: Release
        options:
          - CI
          - Release
          - NoN
      KSU_META:
        type: string
        description: "分支名(不可留空)/自定义版本标识(留空不修改)"
        required: false
        default: "susfs-main/Reeky"
      BUILD_TIME:
        type: string
        description: "自定义构建时间 (输入F使用当前时间)"
        required: false
        default: "F"
      SUFFIX:
        type: string
        description: "自定义内核后缀 (不输入使用随机字符串)"
        required: false
        default: "Reeky"
      FAST_BUILD:
        type: boolean
        description: "是否启用极速构建？"
        required: true
        default: true
      VFS:
        type: boolean
        description: "是否启用手动钩子(VFS)？"
        required: true
        default: true
      TRACEPOINT:
        type: boolean
        description: "是否启用Tracepoint Hook？"
        required: true
        default: false
      KPM:
        type: boolean
        description: "是否启用内核模块(KPM)？"
        required: true
        default: true
      BRUNCH:
        type: string
        description: "輸入內核brunch"
        required: true
        default: "android14-6.1-2025-08"
jobs:
  build:
    name: ${{ github.event.inputs.FAST_BUILD == 'true' && ' [FAST]' || '' }}${{ github.event.inputs.KPM == 'true' && ' [KPM]' || '' }}For ${{ github.event.inputs.SUFFIX }}
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_MAXSIZE: 8G
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: P9P XL config
        run: |
          {
            echo "KANDROID_VERSION=android14"
            echo "KERNEL_VERSION=6.1"
          } >> "$GITHUB_ENV"

      - name: Check Disk Space
        run: df -h

      - name: Create and Enable 3G Swap
        run: |
          sudo swapoff -a
          sudo fallocate -l 3G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Set Cache Environment
        run: |
          echo "CCACHE_DIR=$HOME/.ccache_P9PXL" >> $GITHUB_ENV
          mkdir -p "$HOME/.ccache_P9PXL"
          echo "set: $HOME/.ccache_P9PXL"

      - name: Configure Git
        run: |
          git config --global user.name "topsuplove1122"
          git config --global user.email "topsuplove1122@gmail.com"

      - name: Configure APTC
        run: |
          APT_CACHE_DIR="$HOME/apt-cache"
          mkdir -p "$APT_CACHE_DIR"/{archives,lists/partial}
          echo "Dir::Cache \"$APT_CACHE_DIR\";" | sudo tee /etc/apt/apt.conf.d/90user-cache
          echo "Dir::Cache::archives \"$APT_CACHE_DIR/archives\";" | sudo tee -a /etc/apt/apt.conf.d/90user-cache
          echo "Dir::State::lists \"$APT_CACHE_DIR/lists\";" | sudo tee -a /etc/apt/apt.conf.d/90user-cache
          echo "Acquire::Check-Valid-Until \"false\";" | sudo tee -a /etc/apt/apt.conf.d/90user-cache
          echo "Acquire::Languages \"none\";" | sudo tee -a /etc/apt/apt.conf.d/90user-cache
          sudo chown -R $USER:$USER "$APT_CACHE_DIR"

      - name: Set APT Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/apt-cache
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/Build SukiSU Ultra OnePlus.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install Dependencies
        run: |
          sudo rm -f /var/lib/apt/lists/lock /var/lib/dpkg/lock
          APT_CACHE_DIR="$HOME/apt-cache"
          mkdir -p "$APT_CACHE_DIR/lists/partial"
          sudo apt -o Dir::Cache="$APT_CACHE_DIR" update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt -o Dir::Cache="$APT_CACHE_DIR" install -yq --no-install-recommends \
            python3 git curl ccache libelf-dev \
            build-essential flex bison libssl-dev \
            libncurses-dev liblz4-tool zlib1g-dev \
            libxml2-utils rsync unzip

      - name: Restore Ccache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ github.ref_name }}-P9PXL-${{ env.BUILD_METHOD }}-${{ github.event.inputs.FAST_BUILD == 'true' && 'alpha' || 'beta' }}-15

      - name: Initialize Ccache
        run: |
          INIT_FLAG="${{ env.CCACHE_DIR }}/.ccache_initialized"
          if command -v ccache >/dev/null 2>&1; then
            if [ ! -f "$INIT_FLAG" ]; then
              echo "初始化 ccache (${{ env.CCACHE_DIR }})..."
              mkdir -p "${{ env.CCACHE_DIR }}"
              ccache -M ${{ env.CCACHE_MAXSIZE }}
              touch "$INIT_FLAG"
              echo "✅ ccache 初始化完成"
            else
              echo "✅ ccache 已初始化，跳过"
            fi
          else
            echo "❌ 未安装 ccache，跳过"
          fi
          ccache -s

      - name: Install Repo Tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize Repo and Sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://android.googlesource.com/kernel/manifest -b android-gs-caimito-6.1-android16-beta --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
          repo sync -c -j$(nproc) --no-clone-bundle --no-tags --force-sync 
          rm -rf aosp
          git clone --depth=1 https://android.googlesource.com/kernel/common -b ${{ github.event.inputs.BRUNCH }} aosp
          rm aosp/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm aosp/android/abi_gki_protected_exports_* || echo "No protected exports!"
          sed -i '/"protected_exports_list": "android\/abi_gki_protected_exports_aarch64",/d' aosp/BUILD.bazel
          grep abi_gki_protected_exports_aarch64 aosp/BUILD.bazel || true
          sed -i 's|base_kernel = "//common:kernel_aarch64"|base_kernel = "//aosp:kernel_aarch64"|' private/devices/google/caimito/BUILD.bazel

      - name: Add SukiSU Ultra
        run: |
          cd kernel_workspace/aosp

          META="${{ github.event.inputs.KSU_META }}"
          BRANCH_NAME="${META%%/*}"
          CUSTOM_TAG="${META#*/}"
          echo "分支名: $BRANCH_NAME"
          echo "自定义版本标识: $CUSTOM_TAG"

          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s "$BRANCH_NAME"
          cd ./KernelSU

          KSU_API_VERSION=$(curl -fsSL "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/$BRANCH_NAME/kernel/Makefile" | \
            grep -m1 "KSU_VERSION_API :=" | awk -F'= ' '{print $2}' | tr -d '[:space:]')

          if [[ -z "$KSU_API_VERSION" || "$(printf '%s\n' "$KSU_API_VERSION" "3.1.7" | sort -V | head -n1)" != "3.1.7" ]]; then
            KSU_API_VERSION="3.1.7"
          fi

          echo "KSU_API_VERSION=$KSU_API_VERSION" >> $GITHUB_ENV

          GIT_HASH=$(git rev-parse --short HEAD)
          echo "GIT_HASH=$GIT_HASH"

          if [[ -z "$CUSTOM_TAG" || "$CUSTOM_TAG" == "$BRANCH_NAME" ]]; then
            VERSION_FULL="v$KSU_API_VERSION-$GIT_HASH@$BRANCH_NAME"
          else
            VERSION_FULL="v$KSU_API_VERSION-$CUSTOM_TAG@$BRANCH_NAME[$GIT_HASH]"
          fi

          sed -i '/define get_ksu_version_full/,/endef/d' kernel/Makefile
          sed -i '/KSU_VERSION_API :=/d' kernel/Makefile
          sed -i '/KSU_VERSION_FULL :=/d' kernel/Makefile

          VERSION_DEFINITIONS=$(cat <<EOF
            define get_ksu_version_full
            $VERSION_FULL
            endef

            KSU_VERSION_API := $KSU_API_VERSION
            KSU_VERSION_FULL := $VERSION_FULL
          EOF
          )

          awk -v def="$VERSION_DEFINITIONS" '
            /REPO_OWNER :=/ {print; print def; inserted=1; next}
            1
            END {if (!inserted) print def}
          ' kernel/Makefile > kernel/Makefile.tmp && mv kernel/Makefile.tmp kernel/Makefile

          KSU_VERSION=$(expr $(git rev-list --count main 2>/dev/null || echo 13000) + 10700)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV

          echo "::group::最终 Makefile 中版本信息及部分调试结果预览"
          grep -A10 "REPO_OWNER" kernel/Makefile
          grep "KSU_VERSION_FULL" kernel/Makefile
          echo "::endgroup::"

      - name: Apply Patches SukiSU Ultra
        run: |
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}
          git clone https://github.com/ShirkNeko/SukiSU_patch.git
          cd kernel_workspace
          echo "正在拉取susfs补丁"
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch ./aosp/
          cp ../susfs4ksu/kernel_patches/fs/* ./aosp/fs/
          cp ../susfs4ksu/kernel_patches/include/linux/* ./aosp/include/linux/

          cd ./aosp
          echo "正在打susfs补丁"
          patch -p1 < 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
          echo "susfs_patch完成"

      - name: Apply Hide Stuff Patches
        run: |
          cd kernel_workspace/aosp
          cp ../../SukiSU_patch/69_hide_stuff.patch ./
          echo "正在打隐藏应用补丁"
          patch -p1 -F 3 < 69_hide_stuff.patch
          echo "隐藏应用_patch完成"

      - name: Apply VFS
        if: ${{ github.event.inputs.VFS == 'true' }}
        run: |
          cd kernel_workspace/aosp
          cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
          echo "正在打vfs补丁"
          patch -p1 -F 3 < syscall_hooks.patch
          echo "vfs_patch完成"

      - name: Apply Tracepoint Hook
        if: ${{ github.event.inputs.TRACEPOINT == 'true' }}
        run: |
          cd kernel_workspace/aosp
          curl -LO "https://github.com/topsuplove1122/Build-tool/releases/download/NP3/sukisu_tracepoint_hooks.patch"
          echo "正在打Tracepoint Hook补丁"
          patch -p1 -F 3 < sukisu_tracepoint_hooks.patch
          echo "Tracepoint_Hook_patch完成"

      # 配置信息,带*为附加项目,具有一定危险性和不确定性
      - name: Add Configuration Settings
        run: |
          cd kernel_workspace
          CONFIG_FILE=./aosp/arch/arm64/configs/gki_defconfig
          KERNEL_VERSION="${{ env.KERNEL_VERSION }}"

          # SukiSU Ultra配置
          echo "CONFIG_KSU=y" >> "$CONFIG_FILE"

          # KPM配置
          if [ "${{ github.event.inputs.KPM }}" = "true" ]; then
            echo "CONFIG_KPM=y" >> "$CONFIG_FILE"
          fi

          # VFS配置
          if [ "${{ github.event.inputs.VFS }}" = "true" ]; then
            echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_MANUAL_HOOK=y" >> "$CONFIG_FILE"
          # else
          #   echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> "$CONFIG_FILE"
          #   echo "CONFIG_KPROBES=y" >> "$CONFIG_FILE"
          fi

          # Tracepoint Hook配置
          if [ "${{ github.event.inputs.TRACEPOINT }}" = "true" ]; then
            echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> "$CONFIG_FILE"
            echo "CONFIG_KSU_TRACEPOINT_HOOK=y" >> "$CONFIG_FILE"
          fi

          # SUSFS配置
          echo "CONFIG_KSU_SUSFS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> "$CONFIG_FILE"
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> "$CONFIG_FILE"

          # TMPFS配置*
          echo "CONFIG_TMPFS_XATTR=y" >> "$CONFIG_FILE"
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> "$CONFIG_FILE"

          # BBR配置*
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_BBR=y" >> "$CONFIG_FILE"
          echo "CONFIG_NET_SCH_FQ=y" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_BIC=n" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_CONG_HTCP=n" >> "$CONFIG_FILE"

          # ECN配置*
          echo "CONFIG_IP_ECN=y" >> "$CONFIG_FILE"
          echo "CONFIG_TCP_ECN=y" >> "$CONFIG_FILE"
          echo "CONFIG_IPV6_ECN=y" >> "$CONFIG_FILE"
          echo "CONFIG_IP_NF_TARGET_ECN=y" >> "$CONFIG_FILE"

          # 移除构建审查
          sed -i 's/check_defconfig//' ./aosp/build.config.gki

          #移除maybe-dirty
          
          sed -i '$s|echo "\$res"|echo "\$res-Reeky"|' ./aosp/scripts/setlocalversion
          sed -i '/abi_gki_protected_exports_aarch64/d' ./aosp/BUILD.bazel
          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
          perl -pi -e 's/-maybe-dirty//g' ./build/kernel/kleaf/impl/stamp.bzl
          sed -E -i '/^CONFIG_LOCALVERSION=/ s/(.*)"$/\1-Reeky"/' ./aosp/arch/arm64/configs/gki_defconfig
          sed -i 's/-dirty//' ./aosp/scripts/setlocalversion
          perl -pi -e 's/-dirty//' ./aosp/scripts/setlocalversion

      # Custom kernel build time, without adding #1 SMP PREEMPT 自定义内核构建时间，不要加入#1 SMP PREEMPT
      - name: Custom BUILD_TIME
        shell: bash
        run: |
          INPUT_TIME="${{ github.event.inputs.BUILD_TIME }}"
          if [[ -n "$INPUT_TIME" && "$INPUT_TIME" != *[Ff]* ]]; then
            DATESTR="$INPUT_TIME"
            echo "Using input BUILD_TIME: $DATESTR"
          else
            DATESTR="$(TZ='UTC' date +'%a %b %d %T %Z %Y')"
            echo "Using UTC time as fallback: $DATESTR"
          fi
          echo "KBUILD_BUILD_TIMESTAMP=${DATESTR}" >> "$GITHUB_ENV"
          echo "KBUILD_BUILD_VERSION=1" >> "$GITHUB_ENV"
          cd kernel_workspace/
          for f in aosp/scripts/mkcompile_h; do
            if [ -f "$f" ]; then
              echo "Patching mkcompile_h with BUILD_TIME=$DATESTR"
              if grep -q 'UTS_VERSION=' "$f"; then
                perl -pi -e "s{UTS_VERSION=\"\\\$\\(.*?\\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $DATESTR\"}" "$f"
              else
                perl -0777 -pi -e "s{cat <<EOF}{cat <<EOF\n#undef UTS_VERSION\n#define UTS_VERSION \"#1 SMP PREEMPT $DATESTR\" } unless /UTS_VERSION/" "$f"
              fi
            fi
          done

      - name: Enable lto=thin For FAST
        if: ${{ (env.KERNEL_VERSION == '5.10' || env.KERNEL_VERSION == '5.15') && github.event.inputs.FAST_BUILD == 'true' }}
        run: |
          cd kernel_workspace
          DEFCONFIG=./common/arch/arm64/configs/gki_defconfig
          echo "Enabling ThinLTO in $DEFCONFIG"
          sed -i 's/^CONFIG_LTO=n/CONFIG_LTO=y/' "$DEFCONFIG"
          sed -i 's/^CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "$DEFCONFIG"
          sed -i 's/^CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "$DEFCONFIG"
          grep -q '^CONFIG_LTO_CLANG_THIN=y' "$DEFCONFIG" || echo 'CONFIG_LTO_CLANG_THIN=y' >> "$DEFCONFIG"

      - name: Build Kernel FAST
        if: ${{ github.event.inputs.FAST_BUILD == 'true' }}
        id: fast_build
        run: |
          KERNEL_VERSION="${{ env.KERNEL_VERSION }}"
          if [[ "$KERNEL_VERSION" == "6.6" ]]; then
            CLANG_PATH="clang-r510928"
            CLANG_DIR="prebuilts"
          elif [[ "$KERNEL_VERSION" == "6.1" ]]; then
            CLANG_PATH="clang-r487747c"
            CLANG_DIR="prebuilts"
          elif [[ "$KERNEL_VERSION" == "5.15" ]]; then
            CLANG_PATH="clang-r450784e"
            CLANG_DIR="prebuilts"
          elif [[ "$KERNEL_VERSION" == "5.10" ]]; then
            CLANG_PATH="clang-r416183b"
            CLANG_DIR="prebuilts-master"
            USE_LLVM_IAS=true
          else
            echo "fallback=true" >> "$GITHUB_OUTPUT"
            echo "⚠️ 当前内核版本 \"$KERNEL_VERSION\" 没有对应 clang 工具链，回退使用官方构建脚本"
            echo "请考虑关闭 FAST_BUILD 或补充该版本 clang 路径"
            exit 0
          fi
          export PATH="$GITHUB_WORKSPACE/kernel_workspace/$CLANG_DIR/clang/host/linux-x86/$CLANG_PATH/bin:$PATH"
          export PATH="/usr/lib/ccache:$PATH"
          export CC="ccache clang"
          sudo apt install -y libelf-dev ccache
          cd kernel_workspace/aosp
          # 强制修改 SUBLEVEL，默认关闭
          # sed -i 's/^SUBLEVEL[[:space:]]*=[[:space:]]*.*/SUBLEVEL = 99/' Makefile

          MAKE_ARGS="LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
            RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc \
            PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole \
            LD=ld.lld HOSTLD=ld.lld KCFLAGS+=-Wno-error"
          if [[ "$USE_LLVM_IAS" == "true" ]]; then
            MAKE_ARGS="LLVM_IAS=1 $MAKE_ARGS"
          fi
          make -j$(nproc --all) O=out $MAKE_ARGS gki_defconfig
          make -j$(nproc --all) O=out $MAKE_ARGS
          ccache -s

      - name: Fallback to Build Kernel
        if: ${{ github.event.inputs.FAST_BUILD == 'false' || steps.fast_build.outputs.fallback == 'true' }}
        run: |
          cd kernel_workspace
          ./build_caimito.sh --kernel_package=@//aosp

      - name: Make AnyKernel3
        if: ${{ github.event.inputs.FAST_BUILD == 'false' }}
        run: |
          git clone https://github.com/Numbersf/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          mkdir -p kernel_workspace/out/Final-Image-Find/

          image_path=$(find kernel_workspace/out/ -path "*/bazel-out/*/bin/aosp/kernel_aarch64/Image" ! -path "*/runfiles/*" -print -quit)

          if [ -n "$image_path" ] && [ -f "$image_path" ]; then
            echo "Image file finally located at: $image_path"
            cp "$image_path" ./AnyKernel3/Image
            cp "$image_path" kernel_workspace/out/Final-Image-Find/Image
          fi

      - name: Make AnyKernel3 Fast
        if: ${{ github.event.inputs.FAST_BUILD == 'true' }}
        run: |
          git clone https://github.com/Numbersf/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          mkdir -p kernel_workspace/out/Final-Image-Find/
          dir1=""
          dir2=""
          image_path=$(find "./kernel_workspace/aosp/out/" -name "Image" | head -n 1)
          if [ -n "$image_path" ]; then
            dir1=$(dirname "$image_path")/
            echo "使用 make 编译的统一路径，成功找到 Image 文件"
          else
            image_path=$(find "./kernel_workspace/out/" -name "Image" | head -n 1)
            if [ -n "$image_path" ]; then
              dir2=$(dirname "$image_path")/
              echo "使用官方脚本编译，成功找到 Image 文件"
            else
              echo "未找到 Image 文件，构建失败" >&2
              exit 1
            fi
          fi
          if [ -n "$image_path" ] && [ -f "$image_path" ]; then
            echo "Image file finally located at: $image_path"
            cp "$image_path" ./AnyKernel3/Image
            cp "$image_path" kernel_workspace/out/Final-Image-Find/Image
          fi
          
          

      - name: Make boot for SukiSU
        run: |
          mkdir -p kernel_workspace/out/SukiSU-boot/
          curl -LO "https://github.com/topsuplove1122/Build-tool/releases/download/NP3a-boot/magiskboot"
          curl -LO "https://github.com/topsuplove1122/Build-tool/releases/download/P9PXL/boot.img"
          
          cp ./SukiSU_patch/kpm/patch_linux ./
          cp kernel_workspace/out/Final-Image-Find/Image ./
          chmod +x patch_linux
          chmod +x magiskboot
          ./patch_linux
          rm -rf Image
          ./magiskboot unpack boot.img
          rm -rf kernel
          mv oImage kernel
          ./magiskboot repack boot.img
          rm -rf boot.img
          mv new-boot.img boot.img
          cp boot.img ./kernel_workspace/out/SukiSU-boot/boot_SukiSU_${{ env.KSUVER }}.img
          rm -rf kernel_workspace/out/Final-Image-Find/Image
          rm -rf ./AnyKernel3/Image
          mv kernel Image
          cp Image kernel_workspace/out/Final-Image-Find/
          mv Image ./AnyKernel3/
          

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: boot_SukiSU_${{ env.KSUVER }}
          path: ./kernel_workspace/out/SukiSU-boot/*.img

      
      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
         name: AnyKernel3_SukiSUUltra_${{ env.KSUVER }}_${{ steps.extract_info.outputs.value }}${{ steps.suffix.outputs.value }}
         path: ./AnyKernel3/*

      

      - name: Post-build Disk Check
        run: df -h
